import type { Exercise } from "../schemas/exercise.schema";

export const sampleQuiz: Exercise[] = [
  {
    id: 1,
    type: "FILL_IN_THE_BLANKS",
    description: "___ is your name?",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["Where", "What", "How", "Why"],
    correctAnswer: ["What"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 2,
    type: "MULTIPLE_CHOICE_QUESTION",
    description: "Which of these is a fruit?",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["Carrot", "Potato", "Apple", "Broccoli"],
    correctAnswer: ["Apple"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 3,
    type: "CORRECT_OR_INCORRECT",
    description: "He go to school every day.",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["Correct", "Incorrect"],
    correctAnswer: ["Incorrect"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 4,
    type: "MATCH_THE_COLUMNS",
    description: "Match the greetings with the appropriate times of day.",
    columnA: ["Good morning", "Good afternoon", "Good evening", "Good night"],
    columnB: [
      "Before noon",
      "After lunch",
      "After sunset",
      "Before going to sleep",
    ],
    level: "A1",
    difficulty: "EASY",
    options: [],
    correctAnswer: ["1", "2", "3", "4"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 5,
    type: "UNSCRAMBLE_WORD",
    description: "Fruit",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["e", "o", "a", "r", "n", "g"],
    correctAnswer: ["orange"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 6,
    type: "UNSCRAMBLE_SENTENCE",
    description: "",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["you?", "how", "are"],
    correctAnswer: ["How are you?"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 7,
    type: "LISTENING_COMPREHENSION",
    description: "Over and over again, I'm being ________________",
    columnA: null,
    columnB: null,
    contentUrl:
      "https://www.youtube.com/embed/BL9UMj3Thyg?si=nIiBbXbU76eyXUbh&amp;start=24",
    level: "A1",
    difficulty: "MEDIUM",
    options: [
      "called into your love",
      "cold to your love",
      "called to your love",
      "cold into your love",
    ],
    correctAnswer: ["called into your love"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 8,
    type: "PICTIONARY",
    description: "Look at the picture and choose the correct word.",
    columnA: null,
    columnB: null,
    contentUrl:
      "https://englishconversations-files.s3.us-east-1.amazonaws.com/images/exercise/car.jpg",
    level: "A1",
    difficulty: "EASY",
    options: ["Dog", "Chair", "Car", "Pencil"],
    correctAnswer: ["Car"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 9,
    type: "FREE_ANSWER_QUESTION",
    description: "What is the past form of go?",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: [],
    correctAnswer: ["Went"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
  {
    id: 10,
    type: "TRANSLATION",
    description: "Translate to English: 'Bom dia'",
    columnA: null,
    columnB: null,
    contentUrl: null,
    level: "A1",
    difficulty: "EASY",
    options: ["Good day", "Good afternoon", "Good evening", "Good morning"],
    correctAnswer: ["Good morning"],
    quizId: "cf15d680-8163-4d9c-ab80-938431898a07",
  },
];
