export const ExerciseTypes = {
  FILL_IN_THE_BLANKS: "FILL_IN_THE_BLANKS",
  MULTIPLE_CHOICE_QUESTION: "MULTIPLE_CHOICE_QUESTION",
  CORRECT_OR_INCORRECT: "CORRECT_OR_INCORRECT",
  MATCH_THE_COLUMNS: "MATCH_THE_COLUMNS",
  UNSCRAMBLE_WORD: "UNSCRAMBLE_WORD",
  UNSCRAMBLE_SENTENCE: "UNSCRAMBLE_SENTENCE",
  LISTENING_COMPREHENSION: "LISTENING_COMPREHENSION",
  PICTIONARY: "PICTIONARY",
  FREE_ANSWER_QUESTION: "FREE_ANSWER_QUESTION",
  TRANSLATION: "TRANSLATION",
  SPEAKING_EXERCISE: "SPEAKING_EXERCISE",
  VIDEO_QUESTION: "VIDEO_QUESTION",
} as const;

export type ExerciseTypes = (typeof ExerciseTypes)[keyof typeof ExerciseTypes];
